version: "3.9"
services:
  postgres:
    container_name: postgresql
    image: postgres:16.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=kc-db-user
      - POSTGRES_PASSWORD=kc-db-pass
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - auth-network
  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:23.0.5
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgres # default
      - KEYCLOAK_DATABASE_PORT=5432 # default
      - KEYCLOAK_DATABASE_USER=kc-db-user
      - KEYCLOAK_DATABASE_PASSWORD=kc-db-pass
      - KEYCLOAK_DATABASE_SCHEMA=keycloak-schema
      - KEYCLOAK_DATABASE_NAME=keycloak-db
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - auth-network

  pgadmin:
    hostname: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@dev.com"
      PGADMIN_DEFAULT_PASSWORD: "dev@1234"
    ports:
      - "6001:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - auth-network
volumes:
  postgres:
    driver: local
  pgadmin-data:
    driver: local
networks:
  auth-network:
    name: auth-network
    driver: bridge